name: Example

on:
  push:
    branches:
      - master
      - "push-action/**"
  pull_request:

concurrency:
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install
        run: flutter pub get && cd example

      - name: Analyze
        run: flutter analyze --no-pub

      - name: Test
        run: flutter test --no-pub --coverage
